// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, created_at, updated_at, name, phone_number, email, frequency, start_date, end_date, platform_id, provider_id)
VALUES (
    ?, 
    ?, 
    ?, 
    ?, 
    ?, 
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, name, phone_number, email, created_at, updated_at, frequency, start_date, end_date, provider_id, platform_id
`

type CreateClientParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	PhoneNumber string
	Email       string
	Frequency   string
	StartDate   time.Time
	EndDate     time.Time
	PlatformID  uuid.UUID
	ProviderID  uuid.UUID
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.PhoneNumber,
		arg.Email,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.PlatformID,
		arg.ProviderID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.ProviderID,
		&i.PlatformID,
	)
	return i, err
}

const getClientsByProvider = `-- name: GetClientsByProvider :many
SELECT id, name, phone_number, email, created_at, updated_at, frequency, start_date, end_date, provider_id, platform_id FROM clients
WHERE provider_id = ?
`

func (q *Queries) GetClientsByProvider(ctx context.Context, providerID uuid.UUID) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getClientsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PhoneNumber,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.ProviderID,
			&i.PlatformID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
