// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, created_at, updated_at, name, phone_number, email, platform_id, provider_id)
VALUES (
    ?, 
    ?, 
    ?, 
    ?, 
    ?, 
    ?,
    ?,
    ?
)
RETURNING id, name, phone_number, email, created_at, updated_at, provider_id, platform_id
`

type CreateClientParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	PhoneNumber string
	Email       string
	PlatformID  uuid.UUID
	ProviderID  uuid.UUID
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.PhoneNumber,
		arg.Email,
		arg.PlatformID,
		arg.ProviderID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.PlatformID,
	)
	return i, err
}
