// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID          uuid.UUID
	Name        string
	PhoneNumber string
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProviderID  uuid.UUID
	PlatformID  uuid.UUID
}

type Platform struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Provider struct {
	ID          uuid.UUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Password    string
	PhoneNumber string
	Email       string
}
