// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platforms.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlatform = `-- name: CreatePlatform :one
INSERT INTO platforms (id, created_at, updated_at, name)
VALUES (
    ?, 
    ?, 
    ?, 
    ?
)
RETURNING id, name, created_at, updated_at
`

type CreatePlatformParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error) {
	row := q.db.QueryRowContext(ctx, createPlatform,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformByName = `-- name: GetPlatformByName :one
SELECT id, name, created_at, updated_at FROM platforms
WHERE name = ?
`

func (q *Queries) GetPlatformByName(ctx context.Context, name string) (Platform, error) {
	row := q.db.QueryRowContext(ctx, getPlatformByName, name)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatforms = `-- name: GetPlatforms :many
SELECT id, name, created_at, updated_at FROM platforms
`

func (q *Queries) GetPlatforms(ctx context.Context) ([]Platform, error) {
	rows, err := q.db.QueryContext(ctx, getPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Platform
	for rows.Next() {
		var i Platform
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
