// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (id, created_at, updated_at, name, password, phone_number, email)
VALUES (
    ?, 
    ?, 
    ?, 
    ?, 
    ?, 
    ?,
    ?
)
RETURNING id, name, created_at, updated_at, password, phone_number, email
`

type CreateProviderParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Password    string
	PhoneNumber string
	Email       string
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Password,
		arg.PhoneNumber,
		arg.Email,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, created_at, updated_at, password, phone_number, email FROM providers
WHERE name = ?
`

func (q *Queries) GetProvider(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const getProviderByEmail = `-- name: GetProviderByEmail :one
SELECT id, name, created_at, updated_at, password, phone_number, email FROM providers
WHERE email = ?
`

func (q *Queries) GetProviderByEmail(ctx context.Context, email string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByEmail, email)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const getProviderById = `-- name: GetProviderById :one
SELECT id, name, created_at, updated_at, password, phone_number, email FROM providers 
WHERE id = ?
`

func (q *Queries) GetProviderById(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProviderById, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.PhoneNumber,
		&i.Email,
	)
	return i, err
}

const getProviders = `-- name: GetProviders :many
SELECT id, name, created_at, updated_at, password, phone_number, email FROM providers
`

func (q *Queries) GetProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, getProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.PhoneNumber,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
